project:
  type: book

book:
  title: "Debug_issue_9304"
  author: "Norah Jones"
  date: "4/16/2024"
  
  chapters:
    - index.qmd
    - _chapters/intro.qmd
    - _chapters/summary.qmd
    - _chapters/references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



